name: mise
title: mise-en-place
version: "2025.9.20"
summary: dev tools, env vars, task runner
description: |
  dev tools, env vars, task runner
license: MIT
website: https://mise.jdx.dev/
source-code: https://github.com/phanect/mise-snap
issues: https://github.com/phanect/mise-snap/issues

grade: devel # TODO replace with "stable"
confinement: devmode # TODO use 'classic' or "strict" once you have the right plugs and slots

platforms:
  amd64:
  # arm64:
  # armhf:
  # ppc64el:
  # riscv64:
  # s390x:

base: core24

parts:
  mise:
    source: "https://github.com/jdx/mise.git"
    source-type: git
    source-tag: "v2025.9.20"

    # stage-snaps:
    #   - "ruby/3.4/stable"
    # stage-packages:
    #   - curl
    #   - git

    plugin: rust
    rust-channel: stable

apps:
  mise:
    command: target/release/mise
    plugs:
      - home
      - network
      - network-bind
      - process-control
      - user-config
    # environment:

plugs:
  user-config:
    interface: personal-files
    write:
      - $HOME/.local/share/mise
